services:
  # Backend web service
  - type: web
    name: kmc-membership
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        value: https://kmc-membership.onrender.com/api